### ISSUE TITLE
New website: Problems with `docker compose` command

### ISSUE THREAD

**Issue by xlionjuan** [rustdesk/doc.rustdesk.com#446]
Congrats for the new website, I found the problems with your **Simple self-hosting installation** command:

The command you provided `docker compose up -d` will not work even on Ubuntu 24, it will return

```bash
$ docker compose

docker: 'compose' is not a docker command.
See 'docker --help'
```

Because Ubuntu 24 is still using Docker 24 and it didn't support Compose V2, I checked Fedora 40, it is also on Docker 24, when I installing `docker-compose` package on both Ubuntu 24 and Fedora 40, what they installed is Compose V1, which is still the old one that written by Python, not the V2 one that written by Go, so `docker compose` will still not work.

You have two solutions:
* Add `docker-compose` to your `apt install` command, and replace `docker compose` to `docker-compose`
* Guide user to use [docker/docker-install](https://github.com/docker/docker-install) script, it will auto detect the distro and install latest Docker from Docker official (Current is Docker 27)

https://docs.docker.com/engine/install/

## Second question
When I  `curl rustdesk.com/oss.yml`, I found a space between `network_mode: "host"` and `depends_on:`, `pro.yml` also, you may wanna remove it.

```yml
services:
  hbbs:
    container_name: hbbs
    image: rustdesk/rustdesk-server:latest
    command: hbbs
    volumes:
      - ./data:/root
    network_mode: "host"

    depends_on:
      - hbbr
    restart: unless-stopped

  hbbr:
    container_name: hbbr
    image: rustdesk/rustdesk-server:latest
    command: hbbr
    volumes:
      - ./data:/root
    network_mode: "host"
    restart: unless-stopped
```
